# Generated by Django 2.2.5 on 2019-09-25 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('_personID', models.IntegerField(primary_key=True, serialize=False)),
                ('pId', models.CharField(max_length=20, unique=True)),
                ('pPw', models.CharField(max_length=20)),
                ('pName', models.CharField(max_length=10)),
                ('pBirth', models.CharField(max_length=8)),
                ('pEmail', models.CharField(max_length=30, unique=True)),
                ('pPhone', models.CharField(max_length=11, unique=True)),
                ('pProfile', models.ImageField(blank=True, null=True, upload_to='member_profile/')),
                ('cDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('_memberID', models.IntegerField(primary_key=True, serialize=False)),
                ('introduction', models.CharField(max_length=100, null=True)),
                ('tmi', models.CharField(max_length=100, null=True)),
                ('personID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tkitaka.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('_adminID', models.IntegerField(primary_key=True, serialize=False)),
                ('codeID', models.CharField(max_length=2)),
                ('personID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tkitaka.Person')),
            ],
        ),
    ]
