# Generated by Django 2.2.5 on 2019-09-25 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkitaka', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Administrator',
        ),
        migrations.RenameField(
            model_name='administrator',
            old_name='_adminID',
            new_name='_administratorID',
        ),
    ]
