# Generated by Django 2.2.5 on 2019-09-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkitaka', '0002_auto_20190925_2157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
