# Generated by Django 2.2.5 on 2019-09-25 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tkitaka', '0003_delete_administrator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('_administratorID', models.IntegerField(primary_key=True, serialize=False)),
                ('codeID', models.CharField(max_length=2)),
                ('personID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tkitaka.Person')),
            ],
        ),
    ]
