# Generated by Django 2.2.5 on 2019-09-25 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tkitaka', '0004_administrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='_administratorID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='관리자번호'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='codeID',
            field=models.CharField(max_length=2, verbose_name='관리자 분류'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='personID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tkitaka.Person', verbose_name='사람번호'),
        ),
        migrations.AlterField(
            model_name='member',
            name='_memberID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='회원번호'),
        ),
        migrations.AlterField(
            model_name='member',
            name='introduction',
            field=models.CharField(max_length=100, null=True, verbose_name='자기소개'),
        ),
        migrations.AlterField(
            model_name='member',
            name='personID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tkitaka.Person', verbose_name='사람번호'),
        ),
        migrations.AlterField(
            model_name='member',
            name='tmi',
            field=models.CharField(max_length=100, null=True, verbose_name='PBMS 기타항목'),
        ),
        migrations.AlterField(
            model_name='person',
            name='_personID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='사람번호'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cDate',
            field=models.DateField(auto_now=True, verbose_name='가입날짜'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pBirth',
            field=models.CharField(max_length=8, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pEmail',
            field=models.CharField(max_length=30, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pId',
            field=models.CharField(max_length=20, unique=True, verbose_name='아이디'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pName',
            field=models.CharField(max_length=10, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pPhone',
            field=models.CharField(max_length=11, unique=True, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pProfile',
            field=models.ImageField(blank=True, null=True, upload_to='member_profile/', verbose_name='프로필 사진'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pPw',
            field=models.CharField(max_length=20, verbose_name='비밀번호'),
        ),
    ]
