# Generated by Django 2.2.5 on 2019-09-25 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tkitaka', '0007_auto_20190925_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripInfo',
            fields=[
                ('_tripInfoID', models.AutoField(primary_key=True, serialize=False, verbose_name='여행정보번호')),
                ('codeID', models.CharField(max_length=2, verbose_name='여행정보 분류')),
                ('deDate', models.DateField(verbose_name='출발일')),
                ('reDate', models.DateField(verbose_name='도착일')),
                ('theme', models.CharField(max_length=20, verbose_name='여행 테마')),
                ('age', models.CharField(max_length=10, verbose_name='동행인 연령대')),
                ('isOpen', models.BooleanField(verbose_name='공개 여부')),
                ('cDate', models.DateTimeField(auto_now=True, verbose_name='생성일시')),
                ('uDate', models.DateTimeField(auto_now_add=True, verbose_name='수정일시')),
                ('memberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tkitaka.Member', verbose_name='회원번호')),
            ],
        ),
    ]
