# Generated by Django 2.2.5 on 2019-09-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkitaka', '0008_tripinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cDate',
            field=models.DateField(auto_created=True, auto_now=True, verbose_name='가입날짜'),
        ),
        migrations.AlterField(
            model_name='tripinfo',
            name='cDate',
            field=models.DateTimeField(auto_created=True, auto_now=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='tripinfo',
            name='uDate',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='수정일시'),
        ),
    ]
